---
title: "Working with files"
format: ipynb
editor: visual
jupyter: python3
---

# Working with Files

Why do we care about this?​

-   Data we typically get in the biological sciences are stored in files​

-   If you plan on writing scripts/software, you need to know how to read, write and extract information from files.​

-   Many biological files are stored in text files which are easy to parse and manipulate with python. ​

-   Sequencing Reads​

-   Quality Scores​

-   SNPS​

-   Phylogenetic Trees​

-   Geographical sample data​

-   Etc.​

    ## 

    Arguments for the open function

-   The open function is a Python built-in function to open files.

    -   "r" is for reading​

    -   "w" is for writing​

    -   "a" is for appending​

        -   "w" vs."a"​

        -   If you open a file and use the "w" argument you will overwrite the file.​

        -   If you open an existing file and use the "a" argument you will add new data to the end of the file. ​

        -   Always close your files after you are done reading and writing.

        -   Always use the \# when commenting your code. Comments are helpful as "notes to self" about sections of code

```{python}

import pandas as pd
from pandas import Series, DataFrame

data = open("AOURuralSurvey.csv")

data_contents = data.read() 

print(data_contents)

df = pd.read_csv("AOURuralSurvey.csv")

df
```
